name: Setup Wasmer
description: 'Set up Wasmer: the cross-platform WASM runtime'
author: Wasmer
branding:
  color: purple
  icon: package
runs:
  using: node20
  main: dist/index.js

inputs:
  version:
    default: ''
