# Test the action

name: Tests

on:
  # Run tests when pushed
  push:

env:
  # The string echoed back by Wasmer
  ECHO_STRING: Hello from WASM!

jobs:
  test:
    name: Test on ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      # Setup Wasmer
      - name: Setup Wasmer
        uses: cloud-cnc/setup-wasmer@latest

      # Verify Wasmer is installed
      - name: Verify Wasmer is installed
        shell: pwsh
        run: |
          Get-Command wasmer
          Get-Command wapm
          Get-Command wax

      # Verify Wasmer runs
      - name: Verify Wasmer runs
        uses: MeilCli/test-command-action@v3.0.0
        with:
          command: wapm execute echo ${{ env.ECHO_STRING }}
          expect_contain: ${{ env.ECHO_STRING }}